[package]
name = "clouds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bytemuck = "1.9.1"
rand = "0.8.5"
approx = "0.4"
serde = "1.0"
cameras = {path="../cameras"}
