#[build]
#release = true

[serve]
# The address to serve on.
addr = "127.0.0.1"
# The port to serve on.
port = 3000
# Open a browser tab once the initial build is complete.
open = false
no_autoreload = false

[clean]
cargo = true